<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
      public function byCategorie($categorie)
            
    {
        $qb=$this->createQueryBuilder('u')
               -> select('u')
               ->where('u.category = :categorie')
               ->orderBy('u.id') 
               ->setParameter('categorie', $categorie);
        return $qb->getQuery()->getResult();
                       
          
    }
    
          public function byDepartement($departement)
            
    {
        $qb=$this->createQueryBuilder('u')
               -> select('u')
               ->where('u.departement = :departement')
               ->orderBy('u.id') 
               ->setParameter('departement', $departement);
        return $qb->getQuery()->getResult();
                       
          
    }
    
              public function byRegion($region)
            
    {
        $qb=$this->createQueryBuilder('u')
               -> select('u')
               ->where('u.region = :region')
               ->orderBy('u.id') 
               ->setParameter('region', $region);
        return $qb->getQuery()->getResult();
                       
          
    }
}
