app:
    resource: '@AppBundle/Controller/'
    type: annotation

    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
 
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect
    
facebook_login:
    path: /secured/login_facebook

google_login:
    path: /secured/login_google