imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    default_locale: fr
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    
hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]
    connect:
        account_connector: app.provider.oauth
    resource_owners:
        facebook:
            type:                facebook
            client_id:           353499671791633
            client_secret:       90707d332e620c7a2675aa4e2f91dab6
            scope:               "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email: email
            options:
                display: popup
                auth_type: rerequest
                #csrf: true
        google:
            type:                google
            client_id:           409925945437-47nmhffa3trgtmld14vt7jska3iltas0.apps.googleusercontent.com
            client_secret:       AxxLGrr6t1oyhWuM-rrT56Xl
            scope:              "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email: email
                #twitter Access
        twitter:
            type:                twitter
            client_id:           969171742940909568
            client_secret:       nXXtB5eAKWQvBPSzgTzDmLnlGaFEuzNVJPJGs4rt5xlZpEUiT9
            options:
                include_email: true
    
# FOS Configuration
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:                               
        mailer: fos_user.mailer.twig_swift 
    from_email:
        address: "no-reply@atelier.com"
        sender_name: "atelier.com"
    registration:
        confirmation:
            enabled: true        
#    from_email:
#        address: "%mailer_user%"
#        sender_name: "%mailer_user%"
#    registration: 
#        form:
#            type: AppBundle\form\RegistrationType



#hwi_oauth:
##    http:
##        client: guzzle_client.hwi_special
#    connect:
#        confirmation: true
#        registration_form: fos_user.registration.form.factory
#    firewall_names: [secured_area]
#    fosub:
#        username_iterations: 30
#        properties:
#            facebook: facebookID
#            google: googleID
#            twitter: twitterID
#    resource_owners:
#        #facebook Access
#        facebook:
#            type:                facebook
#            client_id:           1668809379846443
#            client_secret:       90707d332e620c7a2675aa4e2f91dab6
#            options:
#                display: popup
#                auth_type: rerequest
#                csrf: true
#
#        #google Access
#        google:
#            type:                google
#            client_id:           409925945437-47nmhffa3trgtmld14vt7jska3iltas0.apps.googleusercontent.com
#            client_secret:       AxxLGrr6t1oyhWuM-rrT56Xl
#            scope:               "https://www.googleapis.com/auth/plus.login"
#            options:
#                request_visible_actions: "http://schemas.google.com/AddActivity http://schemas.google.com/CommentActivity"
        #twitter Access
#        twitter:
#            type:                twitter
#            client_id:           969171742940909568
#            client_secret:       nXXtB5eAKWQvBPSzgTzDmLnlGaFEuzNVJPJGs4rt5xlZpEUiT9
#            options:
#                include_email: true

